export const coreRuleTerms = [
  {
    id: "test",
    term: "Test",
    aliases: ["Tests", "Test Target"],
    category: "Core Mechanic",
    summary: "Roll 1d100 and compare the result with the relevant characteristic or skill target. A result equal to or below the target succeeds; a higher result fails.",
    book: "Core Rulebook",
    page: "21",
  },
  {
    id: "degrees-of-success",
    term: "Degrees of Success",
    aliases: ["Degree of Success", "DoS"],
    category: "Core Mechanic",
    summary: "The tens digit of the target minus the tens digit of a successful roll, plus one. Degrees measure how well a character succeeds.",
    book: "Core Rulebook",
    page: "24",
  },
  {
    id: "degrees-of-failure",
    term: "Degrees of Failure",
    aliases: ["Degree of Failure", "DoF"],
    category: "Core Mechanic",
    summary: "The tens digit of a failed roll minus the tens digit of the target, plus one. Degrees measure how badly a character fails.",
    book: "Core Rulebook",
    page: "24",
  },
  {
    id: "characteristic-bonus",
    term: "Characteristic Bonus",
    aliases: ["Strength Bonus", "Toughness Bonus", "Agility Bonus", "Intelligence Bonus", "Willpower Bonus", "Influence Bonus"],
    category: "Characteristics",
    summary: "The tens digit of a characteristic. Many rules use this smaller value rather than the full characteristic.",
    book: "Core Rulebook",
    page: "21",
  },
  {
    id: "skill-test",
    term: "Skill Test",
    aliases: ["Skill Tests"],
    category: "Skills",
    summary: "A Test using a skill and its governing characteristic. Training removes the normal untrained penalty and later ranks add bonuses.",
    book: "Core Rulebook",
    page: "23",
  },
  {
    id: "characteristic-test",
    term: "Characteristic Test",
    aliases: ["Characteristic Tests"],
    category: "Core Mechanic",
    summary: "A Test made directly against a characteristic when no skill is more appropriate.",
    book: "Core Rulebook",
    page: "23",
  },
  {
    id: "opposed-test",
    term: "Opposed Test",
    aliases: ["Opposed Tests"],
    category: "Core Mechanic",
    summary: "Both sides make an appropriate Test. The successful side with more Degrees of Success wins; ties are resolved by the higher characteristic bonus.",
    book: "Core Rulebook",
    page: "24",
  },
  {
    id: "extended-test",
    term: "Extended Test",
    aliases: ["Extended Tests"],
    category: "Core Mechanic",
    summary: "A complex task resolved through repeated Tests that accumulate Degrees of Success toward a required total.",
    book: "Core Rulebook",
    page: "24",
  },
  {
    id: "difficulty",
    term: "Difficulty",
    aliases: ["Test Difficulty", "Difficulties"],
    category: "Core Mechanic",
    summary: "A situational modifier applied to the Test target, ranging from large bonuses for simple tasks to severe penalties for punishing ones.",
    book: "Core Rulebook",
    page: "25",
  },
  {
    id: "aptitude",
    term: "Aptitude",
    aliases: ["Aptitudes"],
    category: "Advancement",
    summary: "An affinity that reduces the XP cost of related characteristic, skill, and talent advances. Matching both listed aptitudes gives the lowest cost.",
    book: "Core Rulebook",
    page: "78",
  },
  {
    id: "fate-point",
    term: "Fate Point",
    aliases: ["Fate Points", "Fate Threshold"],
    category: "Fate",
    summary: "A limited resource representing destiny and the Emperor's favour. Fate can be spent for immediate benefits and normally replenishes between sessions.",
    book: "Core Rulebook",
    page: "293",
  },
  {
    id: "wounds",
    term: "Wounds",
    aliases: ["Wound Threshold"],
    category: "Injury",
    summary: "The amount of Damage a character can suffer before excess Damage becomes Critical Damage.",
    book: "Core Rulebook",
    page: "233",
  },
  {
    id: "damage",
    term: "Damage",
    aliases: ["Damage Reduction"],
    category: "Injury",
    summary: "Harm remaining after Armour and Toughness reductions are applied to a hit. Damage accumulates upward.",
    book: "Core Rulebook",
    page: "233",
  },
  {
    id: "critical-damage",
    term: "Critical Damage",
    aliases: ["Critical Effect", "Critical Effects"],
    category: "Injury",
    summary: "Damage beyond the character's Wounds. The excess determines the Critical Effect from the appropriate damage-type and hit-location table.",
    book: "Core Rulebook",
    page: "233",
  },
  {
    id: "fatigue",
    term: "Fatigue",
    aliases: ["Fatigue Threshold"],
    category: "Injury",
    summary: "Strain and exhaustion. Fatigue imposes penalties, and exceeding the character's threshold causes unconsciousness.",
    book: "Core Rulebook",
    page: "233",
  },
  {
    id: "armour",
    term: "Armour",
    aliases: ["Armour Points", "AP"],
    category: "Combat",
    summary: "Protection assigned by hit location. Armour Points reduce incoming Damage, after accounting for the attack's Penetration.",
    book: "Core Rulebook",
    page: "168",
  },
  {
    id: "penetration",
    term: "Penetration",
    aliases: ["Pen"],
    category: "Combat",
    summary: "The amount by which a weapon reduces Armour Points for that hit. Penetration does not reduce Toughness Bonus.",
    book: "Core Rulebook",
    page: "145",
  },
  {
    id: "action",
    term: "Action",
    aliases: ["Actions", "Half Action", "Full Action", "Free Action", "Reaction"],
    category: "Combat",
    summary: "What a character performs during structured time. Actions have types that determine how they fit into a turn.",
    book: "Core Rulebook",
    page: "217",
  },
  {
    id: "acquisition",
    term: "Acquisition",
    aliases: ["Acquisitions", "Acquisition Test"],
    category: "Influence",
    summary: "A request to obtain an item or service using Influence. Availability, quantity, craftsmanship, and circumstances modify the Test.",
    book: "Core Rulebook",
    page: "141",
  },
  {
    id: "influence",
    term: "Influence",
    aliases: ["Influence Bonus"],
    category: "Influence",
    summary: "A characteristic representing reputation, resources, and authority. It is commonly used for acquisitions and social leverage.",
    book: "Core Rulebook",
    page: "22",
  },
  {
    id: "psy-rating",
    term: "Psy Rating",
    aliases: ["PR"],
    category: "Psychic Powers",
    summary: "A psyker's raw psychic strength. Effective Psy Rating affects Focus Power Tests and the scale of many psychic effects.",
    book: "Core Rulebook",
    page: "193",
  },
  {
    id: "focus-power",
    term: "Focus Power Test",
    aliases: ["Focus Power Tests"],
    category: "Psychic Powers",
    summary: "The Test used to manifest a psychic power. The power specifies the characteristic, action, and whether the Test is opposed.",
    book: "Core Rulebook",
    page: "194",
  },
  {
    id: "psychic-phenomena",
    term: "Psychic Phenomena",
    aliases: ["Perils of the Warp"],
    category: "Psychic Powers",
    summary: "Warp disturbances that can occur when psychic powers are used, sometimes escalating into the far more dangerous Perils of the Warp.",
    book: "Core Rulebook",
    page: "195",
  },
  {
    id: "subtlety",
    term: "Subtlety",
    aliases: [],
    category: "Narrative Tools",
    summary: "A warband value reflecting how discreetly it operates. Actions during play can raise or lower it, influencing recognition and opposition.",
    book: "Core Rulebook",
    page: "269",
  },
];

export const characteristicRuleTerms = [
  { id: "characteristic-weapon-skill", term: "Weapon Skill", aliases: ["WS"], category: "Characteristic", summary: "Measures competence in close-quarters combat and governs melee attack Tests.", book: "Core Rulebook", page: "21" },
  { id: "characteristic-ballistic-skill", term: "Ballistic Skill", aliases: ["BS"], category: "Characteristic", summary: "Measures accuracy with ranged weapons and governs ranged attack Tests.", book: "Core Rulebook", page: "21" },
  { id: "characteristic-strength", term: "Strength", aliases: [], category: "Characteristic", summary: "Measures physical power, including lifting, breaking objects, and the force behind melee attacks.", book: "Core Rulebook", page: "21" },
  { id: "characteristic-toughness", term: "Toughness", aliases: [], category: "Characteristic", summary: "Measures health, stamina, and resistance; its bonus helps reduce Damage.", book: "Core Rulebook", page: "21" },
  { id: "characteristic-agility", term: "Agility", aliases: [], category: "Characteristic", summary: "Measures quickness, reflexes, balance, movement, and many forms of evasion.", book: "Core Rulebook", page: "21" },
  { id: "characteristic-intelligence", term: "Intelligence", aliases: [], category: "Characteristic", summary: "Measures reasoning, memory, technical understanding, and the ability to correlate information.", book: "Core Rulebook", page: "21" },
  { id: "characteristic-perception", term: "Perception", aliases: [], category: "Characteristic", summary: "Measures awareness and the sharpness of the character's senses.", book: "Core Rulebook", page: "21" },
  { id: "characteristic-willpower", term: "Willpower", aliases: ["WP"], category: "Characteristic", summary: "Measures mental strength and resilience, including resisting fear and wielding psychic powers.", book: "Core Rulebook", page: "21" },
  { id: "characteristic-fellowship", term: "Fellowship", aliases: [], category: "Characteristic", summary: "Measures persuasiveness, leadership, and force of personality.", book: "Core Rulebook", page: "22" },
  { id: "characteristic-influence", term: "Influence", aliases: [], category: "Characteristic", summary: "Measures reputation, connections, and resources, and is central to obtaining goods and aid.", book: "Core Rulebook", page: "22" },
];

export const skillRuleTerms = [
  { id: "skill-acrobatics", term: "Acrobatics", aliases: [], category: "Skill", summary: "Covers agile movement, balance, controlled falls, and moving past obstacles or opponents without breaking stride.", book: "Core Rulebook", page: "98" },
  { id: "skill-athletics", term: "Athletics", aliases: [], category: "Skill", summary: "Covers climbing, swimming, crossing rough ground, lifting, and pushing through physical exhaustion.", book: "Core Rulebook", page: "99" },
  { id: "skill-awareness", term: "Awareness", aliases: [], category: "Skill", summary: "Notices hidden people, threats, clues, sounds, and other changes in the character's surroundings; it opposes Stealth.", book: "Core Rulebook", page: "100" },
  { id: "skill-charm", term: "Charm", aliases: [], category: "Skill", summary: "Influences another person's attitude through persuasion, generosity, and apparent good intentions rather than threats.", book: "Core Rulebook", page: "100" },
  { id: "skill-command", term: "Command", aliases: [], category: "Skill", summary: "Motivates, organises, and directs allies, including rallying groups and issuing orders in dangerous situations.", book: "Core Rulebook", page: "101" },
  { id: "skill-commerce", term: "Commerce", aliases: [], category: "Skill", summary: "Assesses trade, value, and exchange; it can locate goods, judge prices, and assist with Requisition Tests.", book: "Core Rulebook", page: "102" },
  { id: "skill-common-lore", term: "Common Lore", aliases: [], category: "Skill", summary: "Recalls generally available information about a chosen organisation, culture, region, or field of Imperial life.", book: "Core Rulebook", page: "102" },
  { id: "skill-deceive", term: "Deceive", aliases: [], category: "Skill", summary: "Convinces others of a deliberate falsehood, creates distractions, and supports disguises; it is opposed by Scrutiny.", book: "Core Rulebook", page: "103" },
  { id: "skill-dodge", term: "Dodge", aliases: [], category: "Skill", summary: "A Reaction used to avoid a successful melee or ranged attack; Degrees of Success can cancel additional hits.", book: "Core Rulebook", page: "104" },
  { id: "skill-forbidden-lore", term: "Forbidden Lore", aliases: [], category: "Skill", summary: "Recalls proscribed or secret knowledge in a chosen field, where possessing the information can itself be dangerous.", book: "Core Rulebook", page: "104" },
  { id: "skill-inquiry", term: "Inquiry", aliases: [], category: "Skill", summary: "Gathers information from individuals or groups through questions, conversation, and eavesdropping, usually over an extended period.", book: "Core Rulebook", page: "105" },
  { id: "skill-interrogation", term: "Interrogation", aliases: [], category: "Skill", summary: "Extracts information from an unwilling subject through controlled psychological pressure, devices, or serums in an Opposed Test against Willpower.", book: "Core Rulebook", page: "105" },
  { id: "skill-intimidate", term: "Intimidate", aliases: [], category: "Skill", summary: "Uses fear and coercion to force compliance, extract information, or make an opponent back down; it is opposed by Willpower.", book: "Core Rulebook", page: "106" },
  { id: "skill-linguistics", term: "Linguistics", aliases: [], category: "Skill", summary: "Speaks, reads, writes, translates, and deciphers languages, codes, and ciphers, with a chosen speciality for each trained language.", book: "Core Rulebook", page: "106" },
  { id: "skill-logic", term: "Logic", aliases: [], category: "Skill", summary: "Applies rational analysis, mathematics, and inference to puzzles, complex information, statistics, and likely outcomes.", book: "Core Rulebook", page: "107" },
  { id: "skill-medicae", term: "Medicae", aliases: [], category: "Skill", summary: "Treats injuries and ailments, performs first aid and extended care, diagnoses conditions, and supports surgery or chemical treatment.", book: "Core Rulebook", page: "108" },
  { id: "skill-navigate", term: "Navigate", aliases: [], category: "Skill", summary: "Plots and follows routes, creates maps, and gives directions within the trained surface, stellar, or Warp speciality.", book: "Core Rulebook", page: "110" },
  { id: "skill-operate", term: "Operate", aliases: [], category: "Skill", summary: "Pilots, drives, or operates vehicles and large machines within the trained Surface, Aeronautica, or Voidship speciality.", book: "Core Rulebook", page: "111" },
  { id: "skill-parry", term: "Parry", aliases: [], category: "Skill", summary: "A Reaction used to deflect a melee attack; Degrees of Success can cancel additional melee hits.", book: "Core Rulebook", page: "112" },
  { id: "skill-psyniscience", term: "Psyniscience", aliases: [], category: "Skill", summary: "Senses the currents of the Warp, psychic activity, disturbances, and the presence or effects of immaterial phenomena.", book: "Core Rulebook", page: "112" },
  { id: "skill-scholastic-lore", term: "Scholastic Lore", aliases: [], category: "Skill", summary: "Represents formal study of a chosen field through an institution, knowledgeable mentor, or careful research of learned sources.", book: "Core Rulebook", page: "113" },
  { id: "skill-scrutiny", term: "Scrutiny", aliases: [], category: "Skill", summary: "Analyses people, objects, reports, and readings to uncover lies, motives, inconsistencies, or details requiring careful interpretation.", book: "Core Rulebook", page: "114" },
  { id: "skill-security", term: "Security", aliases: [], category: "Skill", summary: "Bypasses or reinforces locks, codes, cogitator safeguards, physical defences, and traps.", book: "Core Rulebook", page: "115" },
  { id: "skill-sleight-of-hand", term: "Sleight of Hand", aliases: [], category: "Skill", summary: "Uses deception and dexterity to conceal actions, palm or plant objects, pick pockets, and hide items in plain sight.", book: "Core Rulebook", page: "115" },
  { id: "skill-stealth", term: "Stealth", aliases: [], category: "Skill", summary: "Hides, moves silently, blends into crowds, shadows targets, and avoids detection; it is opposed by Awareness.", book: "Core Rulebook", page: "115" },
  { id: "skill-survival", term: "Survival", aliases: [], category: "Skill", summary: "Finds food and water, tracks prey, predicts weather, handles beasts, and creates primitive necessities away from civilisation.", book: "Core Rulebook", page: "116" },
  { id: "skill-tech-use", term: "Tech-Use", aliases: [], category: "Skill", summary: "Operates, repairs, studies, and constructs technological devices through the rites and practical knowledge of the Machine Cult.", book: "Core Rulebook", page: "117" },
  { id: "skill-trade", term: "Trade", aliases: [], category: "Skill", summary: "Practises a chosen craft, identifies its workmanship, recalls trade knowledge, and creates appropriate goods over the required time.", book: "Core Rulebook", page: "118" },
];

export const aptitudeRuleTerms = [
  { id: "aptitude-general", term: "General", aliases: [], category: "Aptitude", summary: "A broad aptitude paired with many common skills and talents when calculating XP costs.", book: "Core Rulebook", page: "78" },
  { id: "aptitude-defence", term: "Defence", aliases: [], category: "Aptitude", summary: "An aptitude associated with avoiding, resisting, and surviving harm.", book: "Core Rulebook", page: "78" },
  { id: "aptitude-fieldcraft", term: "Fieldcraft", aliases: [], category: "Aptitude", summary: "An aptitude associated with awareness, navigation, survival, and operating in the field.", book: "Core Rulebook", page: "78" },
  { id: "aptitude-finesse", term: "Finesse", aliases: [], category: "Aptitude", summary: "An aptitude associated with precision, agility, and carefully placed attacks.", book: "Core Rulebook", page: "78" },
  { id: "aptitude-knowledge", term: "Knowledge", aliases: [], category: "Aptitude", summary: "An aptitude associated with learning, lore, investigation, and reasoned analysis.", book: "Core Rulebook", page: "78" },
  { id: "aptitude-leadership", term: "Leadership", aliases: [], category: "Aptitude", summary: "An aptitude associated with command, coordination, and directing others.", book: "Core Rulebook", page: "78" },
  { id: "aptitude-offence", term: "Offence", aliases: [], category: "Aptitude", summary: "An aptitude associated with aggressive combat techniques and inflicting harm.", book: "Core Rulebook", page: "78" },
  { id: "aptitude-psyker", term: "Psyker", aliases: [], category: "Aptitude", summary: "An aptitude used for psychic powers, Psy Rating, and many Warp-related advances.", book: "Core Rulebook", page: "78" },
  { id: "aptitude-social", term: "Social", aliases: [], category: "Aptitude", summary: "An aptitude associated with persuasion, deception, interrogation, and social influence.", book: "Core Rulebook", page: "78" },
  { id: "aptitude-tech", term: "Tech", aliases: [], category: "Aptitude", summary: "An aptitude associated with machinery, security systems, cybernetics, and technical work.", book: "Core Rulebook", page: "78" },
];

export const creatorRuleTerms = [...coreRuleTerms, ...characteristicRuleTerms, ...skillRuleTerms, ...aptitudeRuleTerms];

export const ruleTermsById = Object.fromEntries(creatorRuleTerms.map((entry) => [entry.id, entry]));

export const contextualRuleTerms = [
  { term: "Aim", aliases: [], category: "Action", summary: "A combat action that grants a bonus to the character's next attack against the chosen target.", book: "Core Rulebook", page: "219" },
  { term: "Standard Attack", aliases: [], category: "Action", summary: "A straightforward melee or ranged attack made as a Half Action.", book: "Core Rulebook", page: "225" },
  { term: "Called Shot", aliases: ["Called Shots"], category: "Action", summary: "An attack directed at a specific hit location, made with an additional penalty.", book: "Core Rulebook", page: "220" },
  { term: "Charge", aliases: [], category: "Action", summary: "Move toward an opponent and make one melee attack with the charge bonus.", book: "Core Rulebook", page: "220" },
  { term: "Overwatch", aliases: [], category: "Action", summary: "Cover a firing zone and attack when a declared trigger occurs.", book: "Core Rulebook", page: "223" },
  { term: "Suppressing Fire", aliases: [], category: "Action", summary: "Fill an area with fire to force enemies into cover and potentially Pin them.", book: "Core Rulebook", page: "225" },
  { term: "Semi-Auto Burst", aliases: ["Semi-Automatic Burst"], category: "Action", summary: "Fire a controlled burst; additional Degrees of Success can score additional hits.", book: "Core Rulebook", page: "224" },
  { term: "Full Auto Burst", aliases: ["Full-Auto Burst"], category: "Action", summary: "Fire a sustained burst; additional Degrees of Success can score additional hits.", book: "Core Rulebook", page: "223" },
  { term: "Dodge", aliases: [], category: "Skill", summary: "An Evasion skill used as a Reaction to avoid a successful attack.", book: "Core Rulebook", page: "104" },
  { term: "Parry", aliases: [], category: "Skill", summary: "A Weapon Skill-based Reaction used to deflect a melee attack.", book: "Core Rulebook", page: "220" },
  { term: "Awareness", aliases: [], category: "Skill", summary: "The skill used to notice threats, clues, unusual details, and hidden opponents.", book: "Core Rulebook", page: "99" },
  { term: "Stealth", aliases: [], category: "Skill", summary: "The skill used to hide, move silently, shadow targets, and avoid detection.", book: "Core Rulebook", page: "115" },
  { term: "Prone", aliases: [], category: "Condition", summary: "A character on the ground is easier to strike in melee and must stand before moving normally.", book: "Core Rulebook", page: "229" },
  { term: "Stunned", aliases: ["Stun"], category: "Condition", summary: "A Stunned character cannot take actions and is easier to attack until the effect ends.", book: "Core Rulebook", page: "230" },
  { term: "Pinned", aliases: ["Pinning"], category: "Condition", summary: "A character affected by suppressive fire must seek cover and has restricted actions until recovery.", book: "Core Rulebook", page: "230" },
  { term: "Surprised", aliases: ["Surprise"], category: "Condition", summary: "A Surprised character cannot act during the opening round and cannot use Reactions until taking a turn.", book: "Core Rulebook", page: "216" },
  { term: "On Fire", aliases: ["Fire"], category: "Condition", summary: "Burning characters suffer ongoing harm and must overcome panic and extinguish the flames.", book: "Core Rulebook", page: "243" },
  { term: "Inquisition", aliases: ["Inquisitor", "Acolyte", "Acolytes"], category: "Faction", summary: "The secretive Imperial institution that investigates and destroys threats to Mankind.", book: "Core Rulebook", page: "18" },
  { term: "Adeptus Mechanicus", aliases: ["Cult Mechanicus", "Tech-Priest", "Tech-Priests"], category: "Faction", summary: "The priesthood of Mars, guardians of Imperial technology and worshippers of the Machine God.", book: "Core Rulebook", page: "50" },
  { term: "Adeptus Astra Telepathica", aliases: ["Astra Telepathica"], category: "Faction", summary: "The Imperial organisation that gathers, tests, sanctions, and trains human psykers.", book: "Core Rulebook", page: "48" },
  { term: "Adeptus Arbites", aliases: ["Arbites"], category: "Faction", summary: "The enforcers of Imperial law and the judgement of the Adeptus Terra.", book: "Core Rulebook", page: "46" },
  { term: "Adeptus Ministorum", aliases: ["Ecclesiarchy"], category: "Faction", summary: "The state church that maintains worship of the Emperor throughout the Imperium.", book: "Core Rulebook", page: "52" },
  { term: "Adeptus Administratum", aliases: ["Administratum"], category: "Faction", summary: "The immense bureaucracy responsible for administering the domains of the Imperium.", book: "Core Rulebook", page: "44" },
  { term: "Imperial Guard", aliases: ["Astra Militarum"], category: "Faction", summary: "The vast armies of the Imperium, formed from countless regiments raised across its worlds.", book: "Core Rulebook", page: "54" },
  { term: "Imperial Navy", aliases: [], category: "Faction", summary: "The Imperial military arm responsible for voidships, fleets, and warfare between the stars.", book: "Enemies Within", page: "32" },
  { term: "Rogue Trader", aliases: ["Rogue Traders"], category: "Faction", summary: "An explorer and potentate granted extraordinary authority by an ancient Warrant of Trade.", book: "Enemies Without", page: "28" },
  { term: "Chaos", aliases: ["Ruinous Powers"], category: "Threat", summary: "The corrupting powers of the Warp and the mortal or daemonic servants who further their designs.", book: "Core Rulebook", page: "17" },
  { term: "Daemon", aliases: ["Daemons", "Daemonic"], category: "Threat", summary: "A hostile entity of the Warp whose presence violates the laws of reality.", book: "Core Rulebook", page: "17" },
  { term: "Xenos", aliases: ["Alien", "Aliens"], category: "Threat", summary: "The Imperial designation for alien species and their works.", book: "Core Rulebook", page: "16" },
  { term: "Psyker", aliases: ["Psykers"], category: "Psychic", summary: "A being able to draw upon the Warp and manifest psychic powers, at grave personal and spiritual risk.", book: "Core Rulebook", page: "90" },
  { term: "Warp", aliases: ["Immaterium"], category: "Psychic", summary: "The psychic dimension underlying reality, used for travel and psychic power but inhabited by terrible entities.", book: "Core Rulebook", page: "17" },
  { term: "Accurate", aliases: [], category: "Quality", summary: "A weapon quality that rewards attacks made with Aim and can add damage on especially successful single shots.", book: "Core Rulebook", page: "145" },
  { term: "Reliable", aliases: [], category: "Quality", summary: "A weapon quality that makes the weapon resistant to jamming.", book: "Core Rulebook", page: "148" },
  { term: "Primitive", aliases: [], category: "Quality", summary: "A weapon or armour quality representing comparatively crude construction and limited effectiveness.", book: "Core Rulebook", page: "147" },
  { term: "Felling", aliases: [], category: "Quality", summary: "A weapon quality that reduces the protection provided by Unnatural Toughness.", book: "Core Rulebook", page: "146" },
];
