// Sourcebook-grounded catalogue for the GM's Reinforcements view.
// These are concise stat references, not reproduced sourcebook pages.

const core = "Dark Heresy Second Edition Core Rulebook";
const within = "Enemies Within";
const without = "Enemies Without";
const beyond = "Enemies Beyond";

const npc = (entry) => ({ type: "npc", ...entry });
const vehicle = (entry) => ({ type: "vehicle", ...entry });

export const reinforcementCatalogue = [
  npc({
    id: "rc-sister-of-battle-canoness",
    name: "Sister of Battle Canoness",
    category: "NPCs",
    source: core,
    page: 297,
    tier: "Master",
    influenceMinimum: 50,
    influenceCost: 5,
    peer: "Peer (Adepta Sororitas) lowers Influence Cost by 2.",
    tags: ["Ecclesiarchy", "Adepta Sororitas", "faith", "warrior"],
    summary: "A holy and divinely ordained warrior called to lead the faithful and punish the heretic.",
    characteristics: { wounds: 22, ws: 50, bs: 45, strength: 35, toughness: 44, agility: 40, intelligence: 32, perception: 31, willpower: 60, fellowship: 55 },
    armour: "Sororitas power armour; Armour 7 to all locations.",
    movement: "Half 4 · Full 8 · Charge 12 · Run 24",
    weapons: [
      "Boltgun — Basic · 100m · S/3/- · 1d10+5 X · Pen 4 · Tearing",
      "Power sword — Melee · 1d10+9+SB E · Pen 5 · Balanced, Power Field",
      "Frag grenades (2) — Blast (3)",
    ],
    skills: ["Awareness +10", "Charm", "Command +20", "Dodge +10", "Linguistics (High Gothic)", "Common Lore (Ecclesiarchy, Imperial Creed) +20", "Forbidden Lore (Heresy) +10", "Scholastic Lore (Imperial Creed) +10", "Scrutiny"],
    talents: ["Adamantium Faith", "Ambidextrous", "Faith Talents", "Hatred (Heretics, Psykers)", "Halo of Command", "Lightning Attack", "Mighty Shot", "Resistance (Psychic Powers)", "Strong-Minded", "Two-Weapon Wielder (Melee, Ranged)", "Weapon Training (Bolter, Power)"],
    traits: ["Unnatural Strength (1)"],
    gear: ["Sororitas power armour", "Micro-bead", "Rebreather", "Recoil glove", "Imperial Creed books and scrolls"],
    fate: 4,
  }),
  npc({
    id: "rc-deathwatch-space-marine",
    name: "Deathwatch Space Marine",
    category: "NPCs",
    source: core,
    page: 298,
    tier: "Master",
    influenceMinimum: 55,
    influenceCost: 7,
    peer: "Peer (Adeptus Astartes) lowers Influence Cost by 2.",
    tags: ["Deathwatch", "Adeptus Astartes", "Ordo Xenos", "warrior"],
    summary: "A veteran Space Marine selected from a Chapter to fight the xenos alongside the Inquisition.",
    characteristics: { wounds: 26, ws: 55, bs: 50, strength: 65, toughness: 45, agility: 40, intelligence: 40, perception: 42, willpower: 44, fellowship: 40 },
    armour: "Astartes power armour; Armour 8 to all locations.",
    movement: "Half 5 · Full 10 · Charge 15 · Run 30",
    weapons: [
      "Astartes bolt pistol — Pistol · 30m · S/2/- · 1d10+9 X · Pen 4 · Reliable",
      "Astartes chainsword — Melee · 1d10+13+SB R · Pen 3 · Balanced, Tearing",
      "Frag grenades (2) — Blast (3)",
      "Krak grenades (2) — 2d10+4 X · Pen 6 · Concussive (0)",
    ],
    skills: ["Athletics +10", "Awareness +10", "Common Lore (War)", "Dodge +10", "Forbidden Lore (Adeptus Astartes, Xenos) +10", "Intimidate +10", "Linguistics (Chapter Runes, High Gothic)", "Navigate (Surface)", "Operate (Surface)", "Parry +10"],
    talents: ["Adamantium Faith", "Ambidextrous", "Bulging Biceps", "Deathwatch Training", "Hatred (Xenos)", "Heightened Senses (Hearing, Sight)", "Peer (Adeptus Astartes, Inquisition)", "Quick Draw", "Resistance (Cold, Heat, Poisons)", "True Grit", "Unarmed Specialist", "Two-Weapon Wielder (Melee, Ranged)", "Weapon Training (Bolter, Chain)"],
    traits: ["Amphibious", "Size (5)", "Unnatural Strength (4)", "Unnatural Toughness (4)"],
    gear: ["Astartes power armour", "Bolt pistol clips", "Tempest and Amputator shells", "Red-dot laser sight and fire selector", "Micro-bead"],
    fate: 3,
  }),
  npc({
    id: "rc-eversor-assassin",
    name: "Eversor Assassin",
    category: "NPCs",
    source: core,
    page: 299,
    tier: "Master",
    influenceMinimum: 60,
    influenceCost: 11,
    peer: "Peer (Officio Assassinorum) lowers Influence Cost by 2.",
    tags: ["Officio Assassinorum", "Eversor", "assassin", "shock attack"],
    summary: "A mind-wiped death machine used to rip the heart out of cults and heretical factions.",
    characteristics: { wounds: 24, ws: 70, bs: 75, strength: 45, toughness: 44, agility: 58, intelligence: 30, perception: 52, willpower: 50, fellowship: 1 },
    armour: "Synskin bodyglove; Armour 3 to all locations.",
    movement: "Half 5 · Full 10 · Charge 15 · Run 30",
    weapons: [
      "Executor pistol (bolt) — Pistol · 30m · S/2/- · 1d10+5 X · Pen 4 · Tearing",
      "Executor pistol (needle) — Pistol · 30m · S/-/- · 1d10 R · Accurate, Felling (1), Toxic (5)",
      "Neuro-gauntlet — Melee · 1d10+10 R · Pen 8 · Tearing, Toxic (3)",
      "Power sword — Melee · 1d10+8+SB E · Pen 6 · Balanced, Power Field",
      "Melta bombs (3) — 6d10 E · Pen 12 · Blast (2), Flame, Melta",
    ],
    skills: ["Athletics +30", "Awareness +20", "Dodge +20", "Operate (Ag) +20", "Security +20", "Stealth +20", "Tech-Use +20"],
    talents: ["Deathdealer (Melee)", "Constant Vigilance", "Temple Assassin", "Unarmed Specialist", "Two-Weapon Master (Melee, Ranged)", "Two-Weapon Wielder (Melee, Ranged)", "Weapon Training (Exotic: Executor Pistol, Power)"],
    traits: ["Fear (2)", "From Beyond", "Unnatural Strength (3)", "Unnatural Toughness (3)"],
    gear: ["Eversor helmet", "Combat drugs", "Sentinel array", "Magnoculars", "Personal medi-kit", "Pict-recorder", "Vox-caster"],
    fate: 2,
    notes: ["Eversor combat drugs offer Hyper-metabolics, Berserker-Slaught, Auto-coagulants, or Shock-stims.", "If killed, the Eversor's body explodes from its combat drugs."],
  }),
  npc({
    id: "rc-grey-knight-space-marine",
    name: "Grey Knight Space Marine",
    category: "NPCs",
    source: core,
    page: 300,
    tier: "Master",
    influenceMinimum: 65,
    influenceCost: 16,
    peer: "Peer (Inquisition) lowers Influence Cost by 2.",
    tags: ["Grey Knights", "Ordo Malleus", "psyker", "daemon hunter"],
    summary: "A shining paladin and psyker, selected from the most promising sanctioned psykers and armed against the Daemon.",
    characteristics: { wounds: 27, ws: 55, bs: 45, strength: 75, toughness: 45, agility: 20, intelligence: 43, perception: 42, willpower: 56, fellowship: 40 },
    armour: "Astartes Terminator Armour; profile includes its characteristic modifiers. Cannot Run or Dodge; Best field rating 35.",
    movement: "Half 3 · Full 6 · Charge 9 · Run 18",
    weapons: [
      "Astartes storm bolter — Basic · 100m · S/2/4 · 1d10+9 X · Pen 4 · Forearm mounting, Razor Sharp, Reliable",
      "Nemesis force halberd — Melee · 1d10+21+PR+SB E · Pen 4+PR · Force, Sanctified, Tearing when used two-handed",
    ],
    skills: ["Athletics +10", "Awareness +10", "Common Lore (War)", "Forbidden Lore (Adeptus Astartes) +10", "Intimidate +20", "Linguistics (Chapter Runes, High Gothic)", "Parry +20", "Psyniscience +20"],
    talents: ["Adamantium Faith", "Bulging Biceps", "Hatred (Daemons, Chaos Space Marines)", "Heightened Senses (Hearing, Sight)", "Peer (Adeptus Astartes, Inquisition)", "Quick Draw", "Resistance (Cold, Heat, Poisons, Psychic Powers)", "Swift Attack", "True Grit", "Unarmed Specialist", "Weapon Training (Bolter, Force)"],
    traits: ["Amphibious", "Psyker (PR 2)", "Size (5)", "Unnatural Strength (4)", "Unnatural Toughness (4)"],
    gear: ["Astartes Terminator Armour", "Storm bolter clips", "Holy texts"],
    psychicPowers: ["Dominate", "Erasure", "Foreboding", "Hammerhand", "Psychic Shriek", "Telepathic Link", "Terrify", "Warp Perception"],
    fate: 2,
  }),
  npc({
    id: "rc-arco-flagellant",
    name: "Arco-Flagellant",
    category: "NPCs",
    source: within,
    page: 41,
    tier: "Elite",
    influenceMinimum: 35,
    influenceCost: 6,
    peer: "Peer (Adeptus Ministorum) lowers Influence Cost by 1d5.",
    tags: ["Ecclesiarchy", "arco-flagellant", "Machine", "melee"],
    summary: "A condemned heretic transformed by surgery, augmetics, and chem-injectors into a controlled killing machine.",
    profileText: "Wounds 30 · WS 53 · BS 40 · T 38 · Ag 45 · Int 10 · Per 41 · WP 20 · Armour 2 all locations",
    movement: "Half 7 · Full 14 · Charge 21 · Run 42",
    weapons: ["Implanted chainaxes — Melee · 1d10+11+4+SB R · Pen 2 · Tearing", "Implanted electro-flails — Melee · 1d10+9+2+SB R · Flexible, Shocking"],
    skills: ["Awareness +10"],
    talents: ["Ambidextrous", "Combat Master", "Devastating Assault", "Iron Jaw", "Lightning Attack", "Melee Weapon Training (Chain, Shock)", "Swift Attack", "Two-Weapon Master", "Two-Weapon Wielder"],
    traits: ["Dark-sight", "Fear (1)", "Machine (2)", "Mindlock", "Unnatural Strength (3)", "Unnatural Agility (3)", "Unnatural Toughness (3)"],
    gear: ["Internal micro-bead", "Machine augmentation and plating", "Chem injectors"],
    notes: ["Triggered Rage, Programmed to Kill, Cannot be Stopped, and Chem Overload are part of the profile."],
    fate: 0,
  }),
  npc({
    id: "rc-penitent-engine",
    name: "Penitent Engine",
    category: "NPCs",
    source: within,
    page: 42,
    tier: "Elite",
    influenceMinimum: 45,
    influenceCost: 5,
    peer: "Peer (Adeptus Ministorum) lowers Influence Cost by 2.",
    tags: ["Ecclesiarchy", "Machine", "Penitent", "walker"],
    summary: "A condemned sinner bonded into a towering bipedal engine and driven by pain, guilt, and retribution.",
    profileText: "Wounds 29 · WS 40 · BS 40 · S 55 · T 40 · Ag 41 · Int 20 · Per 20 · WP 40 · Armour 6 all locations",
    movement: "Half 6 · Full 12 · Charge 18 · Run 36",
    weapons: ["Heavy flamers — Heavy · 30m · S/-/- · 1d10+5 E · Pen 4 · Flame, Spray", "Penitent's chainaxes — Melee · 2d10+8+SB R · Pen 4 · Tearing, Unwieldy"],
    skills: ["Awareness"],
    talents: ["Ambidextrous", "Die Hard", "Frenzy", "Iron Jaw", "Weapon Training (Chain, Flame, Heavy)", "Thunder Charge", "Two-Weapon Master", "Two-Weapon Wielder"],
    traits: ["Auto-stabilised", "Dark-sight", "Machine (6)", "Size (6)", "Unnatural Strength (3)", "Unnatural Toughness (2)"],
    gear: ["Internal micro-bead", "Parchments of sins and prayers", "Extra fuel tanks"],
    notes: ["The Penitent's Rage lets it activate Frenzy as a Half Action. Fury of the Tormented grants Hatred against one foe."],
    fate: 0,
  }),
  npc({
    id: "rc-callidus-assassin",
    name: "Callidus Assassin",
    category: "NPCs",
    source: without,
    page: 41,
    tier: "Master",
    influenceMinimum: 60,
    influenceCost: 11,
    peer: "Peer (Officio Assassinorum) lowers Influence Cost by 2.",
    tags: ["Officio Assassinorum", "Callidus", "infiltration", "assassin"],
    summary: "A master of deception who uses altered flesh and polymorphine to infiltrate and disrupt enemy organisations.",
    characteristics: { wounds: 30, ws: 65, bs: 70, strength: 45, toughness: 44, agility: 64, intelligence: 51, perception: 58, willpower: 55, fellowship: 65 },
    armour: "Synskin bodyglove; Armour 3 to all locations.",
    movement: "Half 6 · Full 12 · Charge 18 · Run 36",
    weapons: ["Neural shredder — Pistol · 20m · S/-/- · 2d10+5 E · Reliable, Shocking, Spray", "Poison blades — Melee · 18m · 1d10+6+SB R · Pen 1 · Razor Sharp, Toxic (4)", "Phase sword — Melee · 1d10+10+4+SB R · Balanced, Felling (4), Proven (5)"],
    skills: ["Acrobatics +10", "Athletics +10", "Awareness +20", "Charm +20", "Deceive +20", "Dodge +20", "Intimidate +10", "Parry +10", "Security +20", "Stealth +20", "Survival +10", "Trade (Chymist) +20"],
    talents: ["Ambidextrous", "Assassin Strike", "Blademaster", "Catfall", "Combat Master", "Constant Vigilance", "Counter Attack", "Cover-Up", "Deathdealer (Melee)", "Deny the Witch", "Face in a Crowd", "Killing Strike", "Temple Assassin", "Two-Weapon Master", "Two-Weapon Wielder", "Unarmed Specialist"],
    traits: ["From Beyond", "Unnatural Strength (2)", "Unnatural Toughness (2)"],
    gear: ["Callidus helmet", "Polymorphine (4 doses)", "Neural shredder reloads", "Magnoculars", "Personal medi-kit", "Pict-recorder", "Vox-caster"],
    fate: 2,
    notes: ["Polymorphine can copy a studied human or humanoid appearance; Temple Assassin grants re-rolls and additional Evasion reactions."],
  }),
  npc({
    id: "rc-kroot-mercenary",
    name: "Kroot Mercenary",
    category: "NPCs",
    source: without,
    page: 42,
    statBlockPage: 103,
    tier: "Troop",
    influenceMinimum: 40,
    influenceCost: 4,
    peer: "Peer (Kroot or Tau) lowers Influence Cost by 2.",
    tags: ["Kroot", "xenos", "mercenary", "scout"],
    summary: "A vigilant avian humanoid mercenary who may be hired across Askellian space despite the attention it can draw.",
    characteristics: { wounds: 12, ws: 42, bs: 33, strength: 40, toughness: 41, agility: 52, intelligence: 26, perception: 44, willpower: 30, fellowship: 19 },
    armour: "Hide armour.",
    movement: "Half 5 · Full 10 · Charge 15 · Run 30",
    weapons: ["Kroot rifle — Basic · 110m · S/2/- · 1d10+5 E · Pen 1", "Beak — Melee · 1d5+6+SB R · Primitive (7)"],
    skills: ["Acrobatics", "Athletics +10", "Awareness", "Dodge +10", "Stealth +20", "Survival +30"],
    talents: ["Furious Assault", "Leap Up", "Sprint", "Swift Attack"],
    traits: ["Eater of the Dead", "Hyperactive Nymune Organ", "Kroot Leap", "Natural Weapons (Beak)", "Unnatural Perception (2)", "Unnatural Strength (2)"],
    gear: ["Bandolier of 30 pulse rounds and 4 sniper rounds", "Chunks of meat", "Totem pouch"],
    fate: 2,
  }),
  npc({
    id: "rc-ork-freeboota",
    name: "Ork Freeboota",
    category: "NPCs",
    source: without,
    page: 42,
    statBlockPage: 88,
    tier: "Elite",
    influenceMinimum: 45,
    influenceCost: 5,
    peer: "Peer (Orks) lowers Influence Cost by 2.",
    tags: ["Ork", "Freeboota", "xenos", "mercenary"],
    summary: "A piratical Ork motivated by profit, adventure, and the opportunity for violence.",
    profileText: "Freeboota (Elite) · Wounds 17 · WS 41 · BS 26 · S 47 · T 46 · Ag 32 · Int 31 · Per 29 · WP 32 · Fel 28",
    movement: "Half 3 · Full 6 · Charge 9 · Run 18",
    weapons: ["Sawn-off snazzgun — Basic · 50m · S/4/8 · 2d10+2 X · Pen 1 · Inaccurate, Overheats, Unreliable", "Kustom choppa — Melee · 1d10+6+1+SB R · Pen 2"],
    skills: ["Athletics", "Dodge", "Intimidate +10", "Commerce", "Survival"],
    talents: ["Crushing Blow", "Technical Knock"],
    traits: ["Unnatural Strength (1)", "Unnatural Toughness (1)"],
    gear: ["Looted armour", "Piratical garb", "Bosspole", "Pouch of Ork teef", "Squig"],
    fate: 2,
  }),
  npc({
    id: "rc-eldar-ranger",
    name: "Eldar Ranger",
    category: "NPCs",
    source: without,
    page: 42,
    statBlockPage: 414,
    tier: "Elite",
    influenceMinimum: 55,
    influenceCost: 7,
    peer: "Peer (Craftworld Eldar) lowers Influence Cost by 2.",
    tags: ["Eldar", "Craftworld", "ranger", "xenos"],
    summary: "A stealth-focused outcast who walks the forgotten paths of the Webway and strikes from concealment.",
    characteristics: { wounds: 12, ws: 42, bs: 49, strength: 37, toughness: 34, agility: 48, intelligence: 39, perception: 42, willpower: 42, fellowship: 4 },
    armour: "Light Eldar mesh armour.",
    movement: "Half 7 · Full 14 · Charge 21 · Run 42",
    weapons: ["Eldar long rifle — Basic · 250m · S/-/- · 1d10+12 E · Pen 2 · Accurate, Felling (2), Reliable"],
    skills: ["Acrobatics +10", "Awareness +10", "Dodge +10", "Stealth +30", "Survival +10"],
    talents: ["Marksman"],
    traits: ["Unnatural Agility (3)", "Unnatural Perception (2)"],
    gear: ["Chameleoline cloak", "Spirit stone"],
    fate: 2,
    notes: ["Living Ghost: two extra degrees of success on successful Stealth tests."],
  }),
  npc({
    id: "rc-rogue-trader",
    name: "Rogue Trader",
    category: "NPCs",
    source: without,
    page: 42,
    statBlockPage: 400,
    tier: "Master",
    influenceMinimum: 50,
    influenceCost: 5,
    peer: "Peer (Rogue Traders) lowers Influence Cost by 2.",
    tags: ["Rogue Trader", "Warrant of Trade", "voidship", "master"],
    summary: "Bearer of a Warrant of Trade, empowered to explore, trade, wage war, and establish colonies beyond Imperial space.",
    characteristics: { wounds: 24, ws: 58, bs: 45, strength: 37, toughness: 33, agility: 46, intelligence: 42, perception: 48, willpower: 50, fellowship: 47 },
    armour: "Carapace armour; Best craftsmanship refractor field.",
    movement: "Half 4 · Full 8 · Charge 12 · Run 24",
    weapons: ["Plasma pistol — Pistol · 30m · S/2/- · 1d10+6 E · Pen 6 · Maximal, Overheats", "Xenos blade — Melee · 1d10+8+5+SB E · Pen 4 · Balanced, Power Field"],
    skills: ["Charm +30", "Commerce +20", "Command +20", "Forbidden Lore (Rogue Traders) +20", "Deceive +20", "Dodge +20", "Parry +20"],
    talents: ["Blade Master", "Combat Master", "Halo of Command", "Quick Draw", "Peer (Rogue Traders)", "Two-Weapon Wielder (Melee, Ranged)"],
    traits: ["Unnatural Fellowship (2)"],
    gear: ["Flamboyant clothing", "Rare trinkets and jewellery", "Best craftsmanship refractor field"],
    fate: 2,
    notes: ["Leverage: once per round, the Rogue Trader may use Influence in place of another characteristic for one test."],
  }),
  npc({
    id: "rc-culexus-assassin",
    name: "Culexus Assassin",
    category: "NPCs",
    source: beyond,
    page: 39,
    tier: "Master",
    influenceMinimum: 60,
    influenceCost: 11,
    peer: "Peer (Officio Assassinorum) lowers Influence Cost by 2.",
    tags: ["Officio Assassinorum", "Culexus", "Untouchable", "psyker hunter"],
    summary: "An Untouchable assassin whose soulless nature and Animus Speculum can extinguish a psyker's life.",
    characteristics: { wounds: 20, ws: 66, bs: 62, strength: 41, toughness: 40, agility: 51, intelligence: 53, perception: 61, willpower: 61, fellowship: 12 },
    armour: "Synskin; Culexus profile includes Phase and other Untouchable protections.",
    movement: "Half 5 · Full 10 · Charge 15 · Run 30",
    weapons: ["Fists — Melee · 1d10+6+SB I · Life Drain", "Psyk-out grenades (3) — Thrown · Blast (3), Smoke (3)", "Arcane Eye — Pistol · 50m · S/-/special · 1d10+6 E · Accurate, Warp Weapon (against psykers and Daemons)"],
    skills: ["Acrobatics +10", "Athletics +10", "Awareness +20", "Dodge +20", "Intimidate +20", "Parry +10", "Survival +20"],
    talents: ["Ambidextrous", "Assassin Strike", "Catfall", "Combat Master", "Constant Vigilance", "Counter Attack", "Deathdealer (Melee)", "Deny the Witch", "Hatred (Psykers)", "Inescapable Attack", "Killing Strike", "Temple Assassin", "Unarmed Specialist"],
    traits: ["Deadly Natural Weapons", "Fear (2)", "From Beyond", "Phase", "Unnatural Strength (2)", "Unnatural Toughness (2)"],
    gear: ["Animus Speculum", "Etherium", "Personal medi-kit", "Pict-recorder", "Synskin bodyglove", "Vox-caster"],
    fate: 2,
    notes: ["Life Drain ignores armour; a successful unarmed hit automatically triggers Righteous Fury."],
  }),
  npc({
    id: "rc-thrice-bound-daemonhost",
    name: "Thrice-Bound Daemonhost",
    category: "NPCs",
    source: beyond,
    page: 40,
    tier: "Master",
    influenceMinimum: 50,
    influenceCost: 5,
    requirements: "The calling Acolyte must possess Forbidden Lore (Daemonology) at Trained level and gains 1d5 Corruption.",
    tags: ["Daemonhost", "Ordo Malleus", "psyker", "daemon"],
    summary: "A Daemon bound by unholy rite into a mortal body; powerful, dangerous, and never completely controlled.",
    characteristics: { wounds: 41, ws: 58, bs: 32, strength: 61, toughness: 50, agility: 14, intelligence: 43, perception: 66, willpower: 68, fellowship: 41 },
    armour: "Rune-inscribed flesh armour; Armour 7 all locations.",
    movement: "Half 2 · Full 4 · Charge 6 · Run 12",
    weapons: ["Claws — Melee · 1d10+13+4+SB R · Pen 4 · Razor Sharp, Tearing"],
    skills: ["Awareness +20", "Deceive +30", "Forbidden Lore (Daemonology, Heresy, the Warp)", "Psyniscience +20"],
    talents: ["Warp Sense"],
    traits: ["Baneful Presence (30)", "Daemonic (3)", "Dark-sight", "Deadly Natural Weapons", "Fear (2)", "From Beyond", "Hover (4)", "Size (5)", "Psyker (PR 4)", "Unnatural Strength (3)"],
    gear: ["Rune-inscribed flesh armour", "Binding chains", "Warding icons"],
    psychicPowers: ["Assail", "Cursed Earth", "Flame Breath", "Psychic Shriek", "Warp Perception"],
    fate: 2,
    notes: ["The GM and players can use the Daemonhost creation rules to shape a patron-specific version."],
  }),
];

export const vehicleCatalogue = [
  vehicle({
    id: "vehicle-glastalk-walker",
    name: "Glasted Walker",
    source: core,
    page: 191,
    category: "Vehicles",
    tags: ["mount", "living", "walker", "Desoleum"],
    summary: "A tall crystalline quadruped adapted to the irradiated plains outside the Desoleum hives.",
    profile: { front: 8, side: 8, rear: 8, cruising: "30 kph", tactical: "5m", manoeuvrability: "+25", size: "Enormous", availability: "Rare", carrying: 0, integrity: 20, threat: 3, crew: "Driver", traits: ["Living", "Open-Topped", "Walker"] },
    weapons: ["Dager Teth — Melee · 1d10+4+SB R · Pen 1"],
    notes: ["Traits: Natural Weapons (Dager Teth), Quadruped, Resistance (Poisons, Radiation)."],
  }),
  vehicle({
    id: "vehicle-hectin-wheeled",
    name: "Hectin Wheeled",
    source: core,
    page: 191,
    category: "Vehicles",
    tags: ["civilian", "wheeled", "Desoleum"],
    summary: "A common Desoleum civilian transport used to carry passengers across hive lanes and habways.",
    profile: { front: 15, side: 10, rear: 8, cruising: "70 kph", tactical: "15m", manoeuvrability: "+10", size: "Enormous", availability: "Rare", carrying: 5, integrity: 20, threat: 5, crew: "Driver", traits: ["Enclosed", "Rugged", "Wheeled"] },
    weapons: ["None by default; an Open-Topped Hectin may mount a separately acquired Basic weapon as a Pintle weapon."],
    notes: ["Gang Wheels replaces Enclosed with Open-Topped and increases Carrying Capacity to 8. Hectins from the Dawn replace Wheeled with Skimmer and become Unique."],
  }),
  vehicle({
    id: "vehicle-veloxic-bike",
    name: "Veloxic Wheeled Bike",
    source: core,
    page: 191,
    category: "Vehicles",
    tags: ["bike", "wheeled", "hive", "Desoleum"],
    summary: "A fast hive bike used by gangs and riders who need excellent handling in crowded levels.",
    profile: { front: 8, side: 8, rear: 8, cruising: "90 kph", tactical: "35m", manoeuvrability: "+20", size: "Hulking", availability: "Very Common", carrying: 0, integrity: 10, threat: 4, crew: "Driver", traits: ["Bike", "Wheeled"] },
    weapons: ["Autogun (armed biker conversion) — Basic · 100m · S/3/- · 1d10+3 I · Pen 0"],
    notes: ["A Veloxic can carry one passenger; while doing so its Manoeuvrability is reduced to +10."],
  }),
  vehicle({
    id: "vehicle-chimera",
    name: "Chimera Tracked",
    source: core,
    page: 192,
    category: "Vehicles",
    tags: ["Imperial Guard", "transport", "tracked", "armoured"],
    summary: "The mainstay Imperial Guard personnel carrier, also used by agencies such as the Adeptus Arbites.",
    profile: { front: 30, side: 22, rear: 16, cruising: "70 kph", tactical: "15m", manoeuvrability: "+0", size: "Massive", availability: "Extremely Rare", carrying: 12, integrity: 35, threat: 30, crew: "Commander (turret), Driver, Gunner (hull weapon)", traits: ["Amphibious", "Enclosed", "Rugged", "Tracked"] },
    weapons: ["Turret choice: Multilaser, Heavy bolter, Autocannon, or Heavy flamer.", "Hull choice: Heavy bolter or Heavy flamer.", "Pintle choice: Storm bolter or Heavy stubber.", "Passenger weaponry: firing ports for Basic or Pistol weapons; may be replaced with lasguns."],
    notes: ["The vehicle carries 12 standard-sized passengers in addition to its crew."],
  }),
  vehicle({
    id: "vehicle-aelurus-trike",
    name: "Aelurus Heavy Trike",
    source: without,
    page: 55,
    category: "Vehicles",
    tags: ["bike", "wheeled", "off-road", "Askellon"],
    summary: "A sturdy off-road trike with modular passenger, cargo, and smuggling configurations.",
    profile: { front: 12, side: 12, rear: 10, cruising: "80 kph", tactical: "18m", manoeuvrability: "+0", size: "Enormous", availability: "Very Common", carrying: 2, integrity: 12, threat: 12, crew: "Driver", traits: ["Bike", "Rugged", "Wheeled"] },
    weapons: ["Optional linked autoguns — Basic · 100m · S/3/10 · 1d10+3 I · Pen 0 · Twin-linked"],
    notes: ["Modular Design can replace passenger seats with cargo or a third passenger seat."],
  }),
  vehicle({
    id: "vehicle-aquila-lander",
    name: "Aquila Lander",
    source: without,
    page: 55,
    category: "Vehicles",
    tags: ["aircraft", "spacecraft", "Imperial", "transport"],
    summary: "An armoured dignitary transport capable of reaching orbital altitude.",
    profile: { front: 24, side: 24, rear: 20, cruising: "2,200 kph", tactical: "1,200m", manoeuvrability: "+10", size: "Immense", availability: "Very Rare", carrying: 10, integrity: 25, threat: 25, crew: "Pilot", traits: ["Enclosed", "Environmentally Sealed", "Flyer", "Skimmer"] },
    weapons: ["Hull choice: Autocannon, Heavy bolter, or Multilaser."],
    notes: ["Ceramite Hull: weapons with Melta do not benefit from that quality against the Lander."],
  }),
  vehicle({
    id: "vehicle-arvus-lighter",
    name: "Arvus Lighter",
    source: without,
    page: 56,
    category: "Vehicles",
    tags: ["aircraft", "spacecraft", "cargo", "Imperial"],
    summary: "A versatile workhorse for cargo, passengers, and occasional assault operations between orbit and the surface.",
    profile: { front: 22, side: 20, rear: 20, cruising: "1,600 kph", tactical: "1,000m", manoeuvrability: "-15", size: "Massive", availability: "Rare", carrying: 10, integrity: 25, threat: 25, crew: "Pilot", traits: ["Enclosed", "Environmentally Sealed", "Flyer", "Rugged"] },
    weapons: ["No standard weapons listed."],
    notes: ["Cargo Hauler: can carry several tonnes of equipment, small gun emplacements, or light vehicles; without cargo, carrying capacity doubles."],
  }),
  vehicle({
    id: "vehicle-sentinel-walker",
    name: "Sentinel Walker",
    source: without,
    page: 57,
    category: "Vehicles",
    tags: ["walker", "Imperial Guard", "cargo", "scout"],
    summary: "A modular hydraulic walker that can move cargo and convert rapidly to scout or combat roles.",
    profile: { front: 15, side: 15, rear: 15, cruising: "45 kph", tactical: "10m", manoeuvrability: "+10", size: "Enormous", availability: "Very Common", carrying: 0, integrity: 20, threat: 18, crew: "Driver", traits: ["Enhanced Motive Systems", "Open-Topped", "Walker"] },
    weapons: ["Hull choice: Powerlifter, Autocannon, Heavy flamer, Lascannon, or Multilaser."],
    notes: ["Armoured Sentinel raises Front Armour to 25, loses Enhanced Motive Systems, and gains Enclosed. A powerlifter can carry up to 3,000 kg."],
  }),
  vehicle({
    id: "vehicle-skerab-walker",
    name: "Skerab Walker",
    source: without,
    page: 58,
    category: "Vehicles",
    tags: ["walker", "titanic", "harvester", "Askellon"],
    summary: "A multi-storey, six-legged walker whose crews live with it as a moving village across Askellon's worlds.",
    profile: { front: 35, side: 35, rear: 35, cruising: "10 kph", tactical: "5m", manoeuvrability: "-30", size: "Titanic", availability: "Common", carrying: 50, integrity: 45, threat: 2, crew: "Drivers, combine operators, enginseer, Tech-adepts, attendant and implanted servitors", traits: ["Damage Control", "Walker"] },
    weapons: ["Combine harvester array — Melee · 8d10+8 R · Pen 6 · Felling (8), Inaccurate, Razor Sharp, Unwieldy", "Earthmover digging shears — Melee · 6d10+4 R · Pen 12 · Concussive (6), Inaccurate, Unwieldy"],
    notes: ["Titanic Behemoth: a Skerab can be treated as a mobile hab block. Anything beneath an active Skerab suffers an automatic hit."],
  }),
  vehicle({
    id: "vehicle-wildcat-buggy",
    name: "Wildcat Transport Buggy",
    source: without,
    page: 58,
    category: "Vehicles",
    tags: ["wheeled", "Faceless Trade", "smuggling", "buggy"],
    summary: "A fast, open transport buggy built to outrun pursuers and carry hidden cargo.",
    profile: { front: 18, side: 15, rear: 15, cruising: "120 kph", tactical: "15m", manoeuvrability: "+15", size: "Enormous", availability: "Rare", carrying: 0, integrity: 15, threat: 18, crew: "Driver, Gunner", traits: ["Enhanced Motive Systems", "Open-Topped", "Wheeled"] },
    weapons: ["Hull autogun — Basic · 100m · S/3/10 · 1d10+3 I · Pen 0.", "Pintle choice: Heavy stubber or Flechette cannon."],
    notes: ["Shielded Cargo imposes -30 on scans; Speed Booster raises speed for six rounds but reduces Manoeuvrability to -20."],
  }),
  vehicle({
    id: "vehicle-reaver-jetbike",
    name: "Reaver Jetbike",
    source: without,
    page: 121,
    category: "Vehicles",
    tags: ["Dark Eldar", "xenos", "bike", "skimmer"],
    summary: "A Dark Eldar jetbike combining a high-speed skimmer with splinter weaponry and blade-vanes.",
    profile: { front: 16, side: 16, rear: 12, cruising: "230 kph", tactical: "40m", manoeuvrability: "+20", size: "Enormous", availability: "Extremely Rare", carrying: 0, integrity: 15, threat: 14, crew: "Pilot", traits: ["Bike", "Enhanced Motive Systems", "Skimmer"] },
    weapons: ["Hull splinter rifle — Basic · 80m · S/3/5 · 1d10+2 R · Pen 3 · Toxic (2).", "Blade-vanes — Melee · 1d10+7 R · Pen 4 · Unwieldy, Hit & Run attacks only."],
    notes: ["The Reaver rider may suffer 1-5 Wounds to automatically succeed on a jetbike Operate test with matching Degrees of Success."],
  }),
];

export const reinforcementById = Object.fromEntries([
  ...reinforcementCatalogue,
  ...vehicleCatalogue,
].map((entry) => [entry.id, entry]));
